version: "3"
services:
  mysql:
    # Sakai requires the database to use UTF-8.
    command: --character-set-server=utf8
    environment:
      # See https://docs.docker.com/samples/library/mysql/#environment-variables
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: bF4EF@^wD&BkFS2Xb2&
      MYSQL_ROOT_PASSWORD: v^Z#bFdz5AyA*LOG3p#
    image: mysql:5.7
  sakai:
    build: .
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql:3306
      DATABASE_NAME: sakai
      DATABASE_USER: sakai
      DATABASE_PASSWORD: bF4EF@^wD&BkFS2Xb2&
    image: byvrate/sakai:12.5
    ports:
      - "3000:3000"